Fix integration tests on Windows with Python 3
Summary:
Python 3's `os.path.join` disallows mixing `str` and `bytes` arguments:

```
$ python3
Python 3.6.2+ (heads/master-dirty:404de642c0, Sep 15 2017, 15:52:01)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ntpath
>>> ntpath.join("hello", b"world")
[snip]
TypeError: Can't mix strings and bytes in path components

>>> import posixpath
>>> posixpath.join("hello", b"world")
[snip]
TypeError: Can't mix strings and bytes in path components
```

`get_canonical_filesystem_path` returns paths as `bytes`. This function is used by `TempDir`, so temp dir paths are `bytes`. Various parts of Watchman's code uses `os.path.join` to join the temp dir path (`bytes`) with other paths represented using `str`. This API misuse leads to a `TypeError`.

For Python 3, make `get_canonical_filesystem_path` return `str` instead of `bytes` so `os.path.join` is happy.

For Python 2.7, keep `get_canonical_filesystem_path` as-is; make it return `str` and not `unicode`.

Reviewed By: wez

Differential Revision: D12983213

fbshipit-source-id: 94fb566cbcff7ccaf4227c9d591869c0e4d82df7