fixup watch_project tests on windows
Summary:
This is a bit speculative, and the goal is to address
the window path normalization issue introduced by D6945540.

Here's an error snippet from the CI logs:

```
AssertionError: 'none of the files listed in global config root_files are
present in path
`C:/cygwin/tmp/watchmantestfhbruz/test_watch_project.TestWatchProjectCliJson.test_watchProjectEnforcing.cli.json/tmpazf_jq-.svn-None-None-False\\a\\b\\c`
or any of its parent directories. root_files is defined by the' not found in
"watchman command error: resolve_projpath: none of the files listed in global
config root_files are present in path
`C:/cygwin/tmp/watchmantestfhbruz/test_watch_project.TestWatchProjectCliJson.test_watchProjectEnforcing.cli.json/tmpazf_jq-.svn-None-None-False/a/b/c`
or any of its parent directories. root_files is defined by the
`C:/ProgramData/facebook/watchman.json` config file and includes
`.watchmanconfig, .git, .hg, .foo, .bar`. One or more of these files must be
present in order to allow a watch. Try pulling and checking out a newer version
of the project?, while executing ('watch-project',
'C:/cygwin/tmp/watchmantestfhbruz/test_watch_project.TestWatchProjectCliJson.test_watchProjectEnforcing.cli.json/tmpazf_jq-.svn-None-None-False\\\\a\\\\b\\\\c')"
```

Reviewed By: simpkins

Differential Revision: D7006606

fbshipit-source-id: f8dab697f69d99eb1dd030eb9500b965583e1c01